### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by DLu** [stereolabs/zed-ros2-interfaces#14]
It would be nice to have this released from the ROS buildfarm so that the folder didn't have to be installed from source for every application.

**Comment by Myzhar** [comment]
@DLu your request is interesting. We are evaluating this internally.

**Comment by Myzhar** [comment]
@DLu The `zed_msgs` package is now available in the official ROS 2 Humble distribution:
`sudo apt install sudo apt install ros-humble-zed-msgs`

**Comment by DLu** [comment]
Fantastic!

**Comment by DLu** [comment]
I would also recommend putting it in the rolling distribution, so that it will be supported in other future distributions.

**Comment by Myzhar** [comment]
Yes, this was a quick release to understand how it works.
I want to add also the other custom topics of the benchmark tool and separate the meshes into their own package
